### PR TITLE
Add support for HEEx files

### PR DESCRIPTION
**Pull request by RodolfoSilva**
This allow to use the extension with `*.heex` files.

### CODE REVIEW

**Comment by RodolfoSilva** [comment]
@alvesoaj do you have any update?

**Comment by alvesoaj** [comment]
> @alvesoaj do you have any update?

Hey, let me check. I believe I can do that today evening.

**Comment by alvesoaj** [comment]
Hey @RodolfoSilva , I just published a new version. Sorry for the very very very long reply. I will take mor care about my personal github emails.

**Comment by alvesoaj** [comment]
Hey @RodolfoSilva , let me know if your additions were enough, or we should add languages and extensions in package.json

**Pull request merged**
